version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/mail-vue"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/mail-worker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"
      - "dependencies"
